
INT_CONFIG(led_type, NVS_KEY_LED_TYPE)
INT_CONFIG(artnet_universe, NVS_KEY_ARTNET_UNIVERSE)
INT_CONFIG(artnet_first_channel, NVS_KEY_ARTNET_FIRST_CHANNEL)
INT_CONFIG(strip_led_count, NVS_KEY_STRIP_LED_COUNT)
INT_CONFIG(strip_pin, NVS_KEY_STRIP_PIN)
INT_CONFIG(r_pin, NVS_KEY_LED_R_PIN)
INT_CONFIG(g_pin, NVS_KEY_LED_G_PIN)
INT_CONFIG(b_pin, NVS_KEY_LED_B_PIN)

INT_CONFIG(button_pin, NVS_KEY_BUTTON_PIN)
